export const PUNCH_MINIMAL_MODE = 'PUNCH_MINIMAL_MODE';
export const FLUSH_MINIMAL_MODE = 'FLUSH_MINIMAL_MODE';

export const REQUEST_USER_WHOAMI = 'REQUEST_USER_WHOAMI';
export const RECEIVE_USER_WHOAMI = 'RECEIVE_USER_WHOAMI';
export const REQUEST_USER_SIGNIN = 'REQUEST_USER_SIGNIN';
export const RECEIVE_USER_SIGNIN = 'RECEIVE_USER_SIGNIN';
export const REQUEST_USER_SIGNOUT = 'REQUEST_USER_SIGNOUT';

export const REQUEST_APPLICATION = 'REQUEST_APPLICATION';
export const RECEIVE_APPLICATION = 'RECEIVE_APPLICATION';
export const REQUEST_APPLICATION_LIST = 'REQUEST_APPLICATION_LIST';
export const RECEIVE_APPLICATION_LIST = 'RECEIVE_APPLICATION_LIST';
export const CREATE_APPLICATION_BEGIN = 'CREATE_APPLICATION_BEGIN';
export const CREATE_APPLICATION_END = 'CREATE_APPLICATION_END';
export const DELETE_APPLICATION_BEGIN = 'DELETE_APPLICATION_BEGIN';
export const DELETE_APPLICATION_END = 'DELETE_APPLICATION_END';
export const REQUEST_TEAMS = 'REQUEST_TEAMS';
export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';
export const CREATE_TEAM_BEGIN = 'CREATE_TEAM_BEGIN';
export const CREATE_TEAM_END = 'CREATE_TEAM_END';
export const DELETE_TEAM_BEGIN = 'DELETE_TEAM_BEGIN';
export const DELETE_TEAM_END = 'DELETE_TEAM_END';

export const REQUEST_AUDIT_LOGS = 'REQUEST_AUDIT_LOGS';
export const RECEIVE_AUDIT_LOGS = 'RECEIVE_AUDIT_LOGS';
export const SYNC_DATE_OF_AUDIT_LOGS = 'SYNC_DATE_OF_AUDIT_LOGS';
export const DISCARD_AUDIT_LOGS = 'DISCARD_AUDIT_LOGS';
export const ROLLBACK_AUDIT_LOG_BEGIN = 'ROLLBACK_AUDIT_LOG_BEGIN';
export const ROLLBACK_AUDIT_LOG_END = 'ROLLBACK_AUDIT_LOG_END';
export const CANCEL_REQUEST_AUDIT_LOGS = 'CANCEL_REQUEST_AUDIT_LOGS';
export const REQUEST_AUDIT_LOGS_END = 'REQUEST_AUDIT_LOGS_END';

export const REQUEST_INSTANCE_AUDIT_LOGS = 'REQUEST_INSTANCE_AUDIT_LOGS';
export const RECEIVE_INSTANCE_AUDIT_LOGS = 'RECEIVE_INSTANCE_AUDIT_LOGS';
export const FETCH_AUDIT_LOGS_END = 'FETCH_AUDIT_LOGS_END';
export const UPDATE_PAGING_LIST = 'UPDATE_PAGING_LIST';

export const ENTER_SUMMIT_HOUR = 'ENTER_SUMMIT_HOUR';
export const LEAVE_SUMMIT_HOUR = 'LEAVE_SUMMIT_HOUR';

export const SNOOZE_BY_SCOPE = 'SNOOZE_BY_SCOPE';

export const PREFERENCE_DATETIME_RELATIVE = 'PREFERENCE_DATETIME_RELATIVE';
export const PREFERENCE_FULL_APPLICATION_TREE = 'PREFERENCE_FULL_APPLICATION_TREE';

export const SUBMIT_INFRA_CONFIG_BEGIN = 'SUBMIT_INFRA_CONFIG_BEGIN';
export const SUBMIT_INFRA_CONFIG_END = 'SUBMIT_INFRA_CONFIG_END';
export const DELETE_INFRA_CONFIG_BEGIN = 'DELETE_INFRA_CONFIG_BEGIN';
export const DELETE_INFRA_CONFIG_END = 'DELETE_INFRA_CONFIG_END';
export const REQUEST_INFRA_DOWNSTREAM = 'REQUEST_INFRA_DOWNSTREAM';
export const RECEIVE_INFRA_DOWNSTREAM = 'RECEIVE_INFRA_DOWNSTREAM';

export const CREATE_INSTANCE_BEGIN = 'CREATE_INSTANCE_BEGIN';
export const CREATE_INSTANCE_END = 'CREATE_INSTANCE_END';
export const DELETE_INSTANCE_BEGIN = 'DELETE_INSTANCE_BEGIN';
export const DELETE_INSTANCE_END = 'DELETE_INSTANCE_END';
export const UPDATE_INSTANCE_STATE_BEGIN = 'UPDATE_INSTANCE_STATE_BEGIN';
export const UPDATE_INSTANCE_STATE_END = 'UPDATE_INSTANCE_STATE_END';
export const FETCH_INSTANCE_LIST_BEGIN = 'FETCH_INSTANCE_LIST_BEGIN';
export const FETCH_INSTANCE_LIST_END = 'FETCH_INSTANCE_LIST_END';
export const FETCH_CLUSTER_LIST_BEGIN = 'FETCH_CLUSTER_LIST_BEGIN';
export const FETCH_CLUSTER_LIST_END = 'FETCH_CLUSTER_LIST_END';
export const CREATE_CLUSTER_BEGIN = 'CREATE_CLUSTER_BEGIN';
export const CREATE_CLUSTER_END = 'CREATE_CLUSTER_BEGIN';
export const DELETE_CLUSTER_BEGIN = 'DELETE_CLUSER_BEIGN';
export const DELETE_CLUSTER_END = 'DELETE_CLUSTER_END';

export const FETCH_SERVICE_INFO_BEGIN = 'FETCH_SERVICE_INFO_BEGIN';
export const FETCH_SERVICE_INFO_END = 'FETCH_SERVICE_INFO_END';
export const CLEAR_SERVICE_INFO_BEGIN = 'CLEAR_SERVICE_INFO_BEGIN';
export const CLEAR_SERVICE_INFO_END = 'CLEAR_SERVICE_INFO_END';
export const PUT_SERVICE_INFO_BEGIN = 'PUT_SERVICE_INFO_BEGIN';
export const PUT_SERVICE_INFO_END = 'PUT_SERVICE_INFO_END';
export const DISCARD_SERVICE_INFO = 'DISCARD_SERVICE_INFO';

export const FETCH_PRIVILEGE_BEGIN = 'FETCH_PRIVILEGE_BEGIN';
export const FETCH_PRIVILEGE_END = 'FETCH_PRIVILEGE_END';
export const CREATE_PRIVILEGE_BEGIN = 'CREATE_PRIVILEGE_BEGIN';
export const CREATE_PRIVILEGE_END = 'CREATE_PRIVILEGE_END';
export const DELETE_PRIVILEGE_BEGIN = 'DELETE_PRIVILEGE_BEGIN';
export const DELETE_PRIVILEGE_END = 'DELETE_PRIVILEGE_END';

export const CHECK_INFRA_CONNECTIVE_BEGIN = 'CHECK_INFRA_CONNECTIVE_BEGIN';
export const CHECK_INFRA_CONNECTIVE_END = 'CHECK_INFRA_CONNECTIVE_END';

export const SET_RELEASE_WINDOW_STATE = 'SET_RELEASE_WINDOW_STATE';
export const SET_RELEASE_WINDOW_BYPASS = 'SET_RELEASE_WINDOW_BYPASS';
export const FETCH_RELEASE_WINDOW_INFO = 'FETCH_RELEASE_WINDOW_INFO';

export const FETCH_SERVICE_ROUTE_BEGIN = 'FETCH_SERVICE_ROUTE_BEGIN';
export const FETCH_SERVICE_ROUTE_END = 'FETCH_SERVICE_ROUTE_END';
export const UPDATE_SERVICE_ROUTE_BEGIN = 'UPDATE_SERVICE_ROUTE_BEGIN';
export const UPDATE_SERVICE_ROUTE_END = 'UPDATE_SERVICE_ROUTE_END';
export const UPDATE_SERVICE_DEFAULT_ROUTE_BEGIN = 'UPDATE_SERVICE_DEFAULT_ROUTE_BEGIN';
export const UPDATE_SERVICE_DEFAULT_ROUTE_END = 'UPDATE_SERVICE_DEFAULT_ROUTE_END';
export const DELETE_SERVICE_ROUTE_BEGIN = 'DELETE_SERVICE_ROUTE_BEGIN';
export const DELETE_SERVICE_ROUTE_END = 'DELETE_SERVICE_ROUTE_END';
export const DELETE_SERVICE_DEFAULT_ROUTE_BEGIN = 'DELETE_SERVICE_DEFAULT_ROUTE_BEGIN';
export const DELETE_SERVICE_DEFAULT_ROUTE_END = 'DELETE_SERVICE_DEFAULT_ROUTE_END';

export const FETCH_WELL_KNOWN_DATA_BEGIN = 'FETCH_WELL_KNOWN_DATA_BEGIN';
export const FETCH_WELL_KNOWN_DATA_END = 'FETCH_WELL_KNOWN_DATA_END';
